Script started on Wed 05 Feb 2020 12:05:50 AM CST
]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ javaMain[K[K[K[K Main
Welcome to the database application!

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 1
Please enter name of your .csv file without the extension: 
Fortune_500_HQ
This database already exists. Would you like to overwrite it? (y/n)
y

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 2
The existing databases are listed below. Please enter which one you would like to open
	Fortune_500_HQ
Database Selection: Fortune_500_HQ
Opening database...

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 7
Please enter the name of the company (truncated at 40 characters): 
doritos
Please enter the city the company is located in (truncated at 20 characters): 
fayetee  teville
Please enter the state the company is located in (truncated at 3 characters): 
ar
Please enter the zip code of the company (truncated at 6 characters): 
72701
Please enter the company's number of employees (truncated at 10 charactes): 
23
Record Added...

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 4
Please enter the name of the company you want to display. 
doritos
501   DORITOS                                  FAYETTEVILLE         AR  72701  23        

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 5
Please enter the name of the company who's record you want to update. 
dortitos
NOT FOUND

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 5
Please enter the name of the company who's record you want to update. 
doritos
What would you like to change?
[1] Rank
[2] City
[3] State
[4] Zip Code
[5] Number of Employees
[6] done updating
1
Enter updated Rank
200
What would you like to change?
[1] Rank
[2] City
[3] State
[4] Zip Code
[5] Number of Employees
[6] done updating
6

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 4
Please enter the name of the company you want to display. 
doritos
200   DORITOS                                  FAYETTEVILLE         AR  72701  23        

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 8
Please enter the name of the company you wish to delete
toritos
That record does not exist in this database

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2]                              FAYETTEVILLE         AR  72701  23        

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 8
Please enter the name of the company you wish to delete
toritos
That record does not exist in this database

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 8
Please enter the name of the company you wish to delete
doritos
Deleting Record...

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 4
Please enter the name of the company you want to display. 
doritos
NOT FOUND

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: q 2
Please close the existing database 'Fortune_500_HQ' first.

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 3
Closing database...

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 2
The existing databases are listed below. Please enter which one you would like to open
	Fortune_500_HQ
Database Selection: q
Invalid database selection
Opening database...

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: q
]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ cat typescript
Script started on Wed 05 Feb 2020 12:05:50 AM CST
]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ javaMain[K[K[K[K Main
Welcome to the database application!

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 1
Please enter name of your .csv file without the extension: 
Fortune_500_HQ
This database already exists. Would you like to overwrite it? (y/n)
y

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 2
The existing databases are listed below. Please enter which one you would like to open
	Fortune_500_HQ
Database Selection: Fortune_500_HQ
Opening database...

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 7
Please enter the name of the company (truncated at 40 characters): 
doritos
Please enter the city the company is located in (truncated at 20 characters): 
fayetee  teville
Please enter the state the company is located in (truncated at 3 characters): 
ar
Please enter the zip code of the company (truncated at 6 characters): 
72701
Please enter the company's number of employees (truncated at 10 charactes): 
23
Record Added...

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 4
Please enter the name of the company you want to display. 
doritos
501   DORITOS                                  FAYETTEVILLE         AR  72701  23        

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 5
Please enter the name of the company who's record you want to update. 
dortitos
NOT FOUND

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 5
Please enter the name of the company who's record you want to update. 
doritos
What would you like to change?
[1] Rank
[2] City
[3] State
[4] Zip Code
[5] Number of Employees
[6] done updating
1
Enter updated Rank
200
What would you like to change?
[1] Rank
[2] City
[3] State
[4] Zip Code
[5] Number of Employees
[6] done updating
6

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 4
Please enter the name of the company you want to display. 
doritos
200   DORITOS                                  FAYETTEVILLE         AR  72701  23        

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 8
Please enter the name of the company you wish to delete
toritos
That record does not exist in this database

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2]]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ mv tye[Kpescript typescript2.script
]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ cat typescript2
cat: typescript2: No such file or directory
]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ cat typescript2.script
Script started on Wed 05 Feb 2020 12:05:50 AM CST
]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ javaMain[K[K[K[K Main
Welcome to the database application!

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 1
Please enter name of your .csv file without the extension: 
Fortune_500_HQ
This database already exists. Would you like to overwrite it? (y/n)
y

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 2
The existing databases are listed below. Please enter which one you would like to open
	Fortune_500_HQ
Database Selection: Fortune_500_HQ
Opening database...

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 7
Please enter the name of the company (truncated at 40 characters): 
doritos
Please enter the city the company is located in (truncated at 20 characters): 
fayetee  teville
Please enter the state the company is located in (truncated at 3 characters): 
ar
Please enter the zip code of the company (truncated at 6 characters): 
72701
Please enter the company's number of employees (truncated at 10 charactes): 
23
Record Added...

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 4
Please enter the name of the company you want to display. 
doritos
501   DORITOS                                  FAYETTEVILLE         AR  72701  23        

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 5
Please enter the name of the company who's record you want to update. 
dortitos
NOT FOUND

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 5
Please enter the name of the company who's record you want to update. 
doritos
What would you like to change?
[1] Rank
[2] City
[3] State
[4] Zip Code
[5] Number of Employees
[6] done updating
1
Enter updated Rank
200
What would you like to change?
[1] Rank
[2] City
[3] State
[4] Zip Code
[5] Number of Employees
[6] done updating
6

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 4
Please enter the name of the company you want to display. 
doritos
200   DORITOS                                  FAYETTEVILLE         AR  72701  23        

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 8
Please enter the name of the company you wish to delete
toritos
That record does not exist in this database

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2]                              FAYETTEVILLE         AR  72701  23        

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 8
Please enter the name of the company you wish to delete
toritos
That record does not exist in this database

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 8
Please enter the name of the company you wish to delete
doritos
Deleting Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: q 2
Please close the existing database 'Fortune_500_HQ' first.

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 3
Closing database...

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 2
The existing databases are listed below. Please enter which one you would like to open
	Fortune_500_HQ
Database Selection: q
Invalid database selection
Opening database...

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: q
]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ cat typescript
Script started on Wed 05 Feb 2020 12:05:50 AM CST
]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ javaMain[K[K[K[K Main
Welcome to the database application!

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 1
Please enter name of your .csv file without the extension: 
Fortune_500_HQ
This database already exists. Would you like to overwrite it? (y/n)
y

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 2
The existing databases are listed below. Please enter which one you would like to open
	Fortune_500_HQ
Database Selection: Fortune_500_HQ
Opening database...

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 7
Please enter the name of the company (truncated at 40 characters): 
doritos
Please enter the city the company is located in (truncated at 20 ]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ mb[Kv typescript2.script typescript.script
]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ 
]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ 
]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ 
]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ 
]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ 
]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ 
]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ 
]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ 
]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ 
]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ ^C
]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ cat typescript.script
Script started on Wed 05 Feb 2020 12:05:50 AM CST
]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ javaMain[K[K[K[K Main
Welcome to the database application!

Please enter which operation number yo0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ 
]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ 
]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ ^C
]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ cat typescript.script
Script started on Wed 05 Feb 2020 12:05:50 AM CST
]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ javaMain[K[K[K[K Main
Welcome to the database application!

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 1
Please enter name of your .csv file without the extension: 
Fortune_500_HQ
This database already exists. Would you like to overwrite it? (y/n)
y

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 2
The existing databases are listed below. Please enter which one you would like to open
	Fortune_500_HQ
Database Selection: Fortune_500_HQ
Opening database...

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 7
Please enter the name of the company (truncated at 40 characters): 
doritos
Please enter the city the company is located in (truncated at 20 characters): 
fayetee  teville
Please enter the state the company is located in (truncated at 3 characters): 
ar
Please enter the zip code of the company (truncated at 6 characters): 
72701
Please enter the company's number of employees (truncated at 10 charactes): 
23
Record Added...

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 4
Please enter the name of the company you want to display. 
doritos
501   DORITOS                                  FAYETTEVILLE         AR  72701  23        

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 5
Please enter the name of the company who's record you want to update. 
dortitos
NOT FOUND

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 5
Please enter the name of the company who's record you want to update. 
doritos
What would you like to change?
[1] Rank
[2] City
[3] State
[4] Zip Code
[5] Number of Employees
[6] done updating
1
Enter updated Rank
200
What would you like to change?
[1] Rank
[2] City
[3] State
[4] Zip Code
[5] Number of Employees
[6] done updating
6

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 4
Please enter the name of the company you want to display. 
doritos
200   DORITOS                                  FAYETTEVILLE         AR  72701  23        

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 8
Please enter the name of the company you wish to delete
toritos
That record does not exist in this database

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2]                              FAYETTEVILLE         AR  72701  23        

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 8
Please enter the name of the company you wish to delete
toritos
That record does not exist in this database

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 8
Please enter the name of the company you wish to delete
doritos
Deleting Record...

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 4
Please enter the name of the company you want to display. 
doritos
NOT FOUND

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: q 2
Please close the existing database 'Fortune_500_HQ' first.

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 3
Closing database...

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 2
The existing databases are listed below. Please enter which one you would like to open
	Fortune_500_HQ
Database Selection: q
Invalid database selection
Opening database...

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: q
]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ cat typescript
Script started on Wed 05 Feb 2020 12:05:50 AM CST
]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ javaMain[K[K[K[K Main
Welcome to the database application!

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 1
Please enter name of your .csv file without the extension: 
Fortune_500_HQ
This database already exists. Would you like to overwrite it? (y/n)
y

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Records): 
doritos
Please enter the city the company is located in (truncated at 20 characters): 
fayetee  teville
Please enter the state the company is located in (truncated at 3 characters): 
ar
Please enter the zip code of the company (truncated at 6 characters): 
72701
Please enter the company's number of employees (truncated at 10 charactes): 
23
Record Added...

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 4
Please enter the name of the company you want to display. 
doritos
501   DORITOS                                  FAYETTEVILLE         AR  72701  23        

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 5
Please enter the name of the company who's record you want to update. 
dortitos
NOT FOUND

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 5
Please enter the name of the company who's record you want to update. 
doritos
What would you like to change?
[1] Rank
[2] City
[3] State
[4] Zip Code
[5] Number of Employees
[6] done updating
1
Enter updated Rank
200
What would you like to change?
[1] Rank
[2] City
[3] State
[4] Zip Code
[5] Number of Employees
[6] done updating
6

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 4
Please enter the name of the company you want to display. 
doritos
200   DORITOS                                  FAYETTEVILLE         AR  72701  23        

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 8
Please enter the name of the company you wish to delete
toritos
That record does not exist in this database

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2]]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ mv tye[Kpescript typescript2.script
]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ cat typescript2
cat: typescript2: No such file or directory
]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ cat typescript2.script
Script started on Wed 05 Feb 2020 12:05:50 AM CST
]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ javaMain[K[K[K[K Main
Welcome to the database application!

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 1
Please enter name of your .csv file without the extension: 
Fortune_500_HQ
This database already exists. Would you like to overwrite it? (y/n)
y

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 1
Please enter name of your .csv file without the extension: 
Fortune_500_HQ
This database already exists. Would you like to overwrite it? (y/n)
y

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 2
The existing databases are listed below. Please enter which one you would like to open
	Fortune_500_HQ
Database Selection: Fortune_500_HQ
Opening database...

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 7
Please enter the name of the company (truncated at 40 characters): 
doritos
Please enter the city the company is located in (truncated at 20 characters): 
fayetee  teville
Please enter the state the company is located in (truncated at 3 characters): 
ar
Please enter the zip code of the company (truncated at 6 characters): 
72701
Please enter the company's number of employees (truncated at 10 charactes): 
23
Record Added...

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 4
Please enter the name of the company you want to display. 
doritos
501   DORITOS                                  FAYETTEVILLE         AR  72701  23        

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 5
Please enter the name of the company who's record you want to update. 
dortitos
NOT FOUND

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 5
Please enter the name of the company who's record you want to update. 
doritos
What would you like to change?
[1] Rank
[2] City
[3] State
[4] Zip Code
[5] Number of Employees
[6] done updating
1
Enter updated Rank
200
What would you like to change?
[1] Rank
[2] City
[3] State
[4] Zip Code
[5] Number of Employees
[6] done updating
6

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 4
Please enter the name of the company you want to display. 
doritos
200   DORITOS                                  FAYETTEVILLE         AR  72701  23        

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 8
Please enter the name of the company you wish to delete
toritos
That record does not exist in this database

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2]                              FAYETTEVILLE         AR  72701  23        

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 8
Please enter the name of the company you wish to delete
toritos
That record does not exist in this database

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 8
Please enter the name of the company you wish to delete
doritos
Deleting Record...

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 4
Please enter the name of the company you want to display. 
doritos
NOT FOUND

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: q 2
Please close the existing database 'Fortune_500_HQ' first.

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 3
Closing database...

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 2
The existing databases are listed below. Please enter which one you would like to open
	Fortune_500_HQ
Database Selection: q
Invalid database selection
Opening database...

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: q
]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ cat typescript
Script started on Wed 05 Feb 2020 12:05:50 AM CST
]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ javaMain[K[K[K[K Main
Welcome to the database application!

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 1
Please enter name of your .csv file without the extension: 
Fortune_500_HQ
This database already exists. Would you like to overwrite it? (y/n)
y

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 2
The existing databases are listed below. Please enter which one you would like to open
	Fortune_500_HQ
Database Selection: Fortune_500_HQ
Opening database...

Please enter which operation 