Script started on Tue 04 Feb 2020 09:26:16 PM CST
]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ javac *.java
]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ java Main
Welcome to the database application!

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 2
There are no existing databases. Please create one.
Database Selection: 1
Invalid database selection

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: hello
Invalid option selected. Please try again!

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 1
Please enter name of your .csv file without the extension: 
Fortune_4 500_h HQ

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 4
There is no database currently open.

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 2
The existing databases are listed below. Please enter which one you would like to open
	Fortune_500_HQ
Database Selection: hello
Invalid database selection

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 2
The existing databases are listed below. Please enter which one you would like to open
	Fortune_500_HQ
Database Selection: Fortune_500) _HQ

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 4
Please enter the name of the company you want to display. 
walmart
1     WALMART                                  BENTONVILLE          AR  72716  2300000   

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 4
Please enter the name of the company you want to display. 
hello
NOT FOUND

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 5
Please enter the name of the company who's record you want to update. 
walmart
What would you like to change?
[1] Rank
[2] City
[3] State
[4] Zip Code
[5] Number of Employees
[6] done updating
1
Enter updated Rank
1000
What would you like to change?
[1] Rank
[2] City
[3] State
[4] Zip Code
[5] Number of Employees
[6] done updating
6

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 4
Please enter the name of the company you want to display. 
walmart
1000  WALMART                                  BENTONVILLE          AR  72716  2300000   

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 5
Please enter the name of the company who's record you want to update. 
walmart
What would you like to change?
[1] Rank
[2] City
[3] State
[4] Zip Code
[5] Number of Employees
[6] done updating
1
Enter updated Rank
500
What would you like to change?
[1] Rank
[2] City
[3] State
[4] Zip Code
[5] Number of Employees
[6] done updating
2
Enter updated City
Columbus
What would you like to change?
[1] Rank
[2] City
[3] State
[4] Zip Code
[5] Number of Employees
[6] done updating
3
Enter updated State Abbreviation
e Georgia
What would you like to change?
[1] Rank
[2] City
[3] State
[4] Zip Code
[5] Number of Employees
[6] done updating
4
Enter updated Zip Code
31820
What would you like to change?
[1] Rank
[2] City
[3] State
[4] Zip Code
[5] Number of Employees
[6] done updating
5
Enter updated Number of Employees
23
What would you like to change?
[1] Rank
[2] City
[3] State
[4] Zip Code
[5] Number of Employees
[6] done updating
6

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 4
Please enter the name of the company you want to display. 
walmart
500   WALMART                                  COLUMBUS             GEO 31820  23        

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 7
Please enter the name of the company (truncated at 40 characters): 
Doruts   itos
Please enter the city the company is located in (truncated at 20 characters): 
Fayetteville
Please enter the state the company is located in (truncated at 3 characters): 
Arkansas       R
Please enter the zip code of the company (truncated at 6 characters): 
318209
Please enter the company's number of employees (truncated at 10 charactes): 
2300000
Record Added...

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 4
Please enter the name of the company you want to display. 
doer  ritos
501   DORITOS                                  FAYETTEVILLE         AR  318209 2300000   

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 8
Please enter the name of the company you wish to delete
walmart
Deleting Record...

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 4
Please enter the name of the company you want to display. 
walmart
NOT FOUND

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 8
Please enter the name of the company you wish to delete
doritos
Deleting Record...

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 4
Please enter the name of the company you want to display. 
doritos
NOT FOUND

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 2
Please close the existing database 'Fortune_500_HQ' first.

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 3
Closing database...

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 1
Please enter name of your .csv file without the extension: 
Fortun ne_500_HQ
This database already exists. Would you like to overwrite it? (y/n)
y

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 4
There is no database currently open.

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: walmart
Invalid option selected. Please try again!

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 2
The existing databases are listed below. Please enter which one you would like to open
	Fortune_500_HQ
Database Selection: Fortune_500_HQ
Opening database...

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: 4
Please enter the name of the company you want to display. 
walmart
1     WALMART                                  BENTONVILLE          AR  72716  2300000   

Please enter which operation number you would like to complete (or enter 'q' to quit):

	[1] Create Database
	[2] Open Database
	[3] Close Database
	[4] Display Record
	[5] Update Record
	[6] Create Report
	[7] Add Record
	[8] Delete Record

Selection: q
]0;grdirkso@turing: ~/databaseProject1grdirkso@turing:~/databaseProject1$ cat typescript                                                                                                                                            